/**
 * Subtitles, whose whole difficulty is that the file is cut for a screen and
 * the reader wants sentences.
 *
 * The fixtures are written the way the real files arrive — CRLF, a BOM, cue
 * settings, inline timestamp tags, and the rolling repetition YouTube's
 * automatic captions carry — because every one of those is something that broke
 * a naive parser first.
 */

import { describe, expect, it } from 'vitest';

import { splitSentences } from './sentences';
import { cuesToSentences, detectSubtitleFormat, parseSubtitles } from './subtitles';

const SRT = `1
00:00:01,000 --> 00:00:03,500
Fuimos al restaurante y
pedimos sopa.

2
00:00:03,500 --> 00:00:06,000
La cuenta no era cara. Dejamos
una propina.
`;

const VTT = `WEBVTT
Kind: captions
Language: zh

NOTE
This file was generated by a machine.

intro
00:00:01.000 --> 00:00:03.000 align:start position:0%
<v Speaker>我们去了<i>饭馆</i>。</v>
我点了汤。

00:00:03.000 --> 00:00:05.000
她点了鱼
和米饭。
`;

/**
 * What `yt-dlp --write-auto-subs` actually produces: a rolling two-line window,
 * a ten-millisecond transition cue between every pair, an empty top line where
 * the window has not filled yet, and per-word timestamps inside `<c>` spans.
 */
const ROLLING_VTT = `WEBVTT
Kind: captions
Language: zh

00:00:00.030 --> 00:00:03.270 align:start position:0%

大家好<00:00:00.630><c>欢迎</c><00:00:01.240><c>来到</c>

00:00:03.270 --> 00:00:03.280 align:start position:0%
大家好欢迎来到


00:00:03.280 --> 00:00:06.140 align:start position:0%
大家好欢迎来到
我的<00:00:04.000><c.colorE5E5E5>频道</c>

00:00:06.140 --> 00:00:06.150 align:start position:0%
我的频道


00:00:06.150 --> 00:00:09.000 align:start position:0%
我的频道
今天<00:00:07.000><c>我们</c><00:00:07.500><c>聊聊</c>
`;

const PANEL = `0:00
第一句话。
0:04
第二句话。
1:02:33
最后一句。`;

describe('detectSubtitleFormat', () => {
	it('knows the three shapes a learner turns up with', () => {
		expect(detectSubtitleFormat(SRT)).toBe('srt');
		expect(detectSubtitleFormat(VTT)).toBe('vtt');
		expect(detectSubtitleFormat(PANEL)).toBe('youtube-transcript');
	});

	it('sees through a BOM and CRLF line endings', () => {
		expect(detectSubtitleFormat('﻿' + VTT.replace(/\n/g, '\r\n'))).toBe('vtt');
		expect(detectSubtitleFormat(SRT.replace(/\n/g, '\r\n'))).toBe('srt');
	});

	it('leaves ordinary prose alone, timestamps in it or not', () => {
		expect(detectSubtitleFormat('Fuimos al restaurante. Pedí sopa.')).toBeUndefined();
		expect(detectSubtitleFormat('El tren sale a las 9:30 y llega a las 11:45.')).toBeUndefined();
		expect(detectSubtitleFormat('')).toBeUndefined();
		expect(detectSubtitleFormat('   \n  ')).toBeUndefined();
	});

	it('wants more than one timed line before it calls something a transcript', () => {
		expect(detectSubtitleFormat('0:00\nUna sola línea.')).toBeUndefined();
	});
});

describe('parseSubtitles', () => {
	it('reads SRT blocks and joins their lines with a space', () => {
		expect(parseSubtitles(SRT)).toEqual([
			{ start: 1000, end: 3500, text: 'Fuimos al restaurante y pedimos sopa.' },
			{ start: 3500, end: 6000, text: 'La cuenta no era cara. Dejamos una propina.' }
		]);
	});

	it('skips the VTT header, notes, identifiers and settings, and strips markup', () => {
		expect(parseSubtitles(VTT)).toEqual([
			{ start: 1000, end: 3000, text: '我们去了饭馆。我点了汤。' },
			{ start: 3000, end: 5000, text: '她点了鱼和米饭。' }
		]);
	});

	it('joins CJK lines with no separator and Latin lines with a space', () => {
		expect(parseSubtitles(VTT)[0].text).not.toContain(' ');
		expect(parseSubtitles(SRT)[0].text).toContain('y pedimos');
	});

	it('decodes the entities a subtitle file actually carries', () => {
		const cues = parseSubtitles(`1
00:00:01,000 --> 00:00:02,000
Ben &amp; Jerry said &lt;hello&gt;&nbsp;there
`);
		expect(cues[0].text).toBe('Ben & Jerry said <hello> there');
	});

	it('reads a transcript panel, ending each cue where the next begins', () => {
		expect(parseSubtitles(PANEL)).toEqual([
			{ start: 0, end: 4000, text: '第一句话。' },
			{ start: 4000, end: 3753000, text: '第二句话。' },
			{ start: 3753000, end: 3757000, text: '最后一句。' }
		]);
	});

	it('returns nothing for a text that is not subtitles at all', () => {
		expect(parseSubtitles('Fuimos al restaurante.')).toEqual([]);
	});

	describe('rolling auto-generated captions', () => {
		const cues = parseSubtitles(ROLLING_VTT);

		it('emits every line exactly once', () => {
			expect(cues.map((cue) => cue.text)).toEqual(['大家好欢迎来到', '我的频道', '今天我们聊聊']);
		});

		it('drops the transition cues, so nothing is left empty or repeated', () => {
			expect(cues).toHaveLength(3);
			expect(cues.every((cue) => cue.text.trim() !== '')).toBe(true);
		});

		it('gives a line the timing of the cue it first appeared in', () => {
			expect(cues[0].start).toBe(30);
			expect(cues[1].start).toBe(3280);
			expect(cues[2].start).toBe(6150);
			expect(cues[2].end).toBe(9000);
		});

		it('keeps the first line, which a blank-line split would have orphaned', () => {
			expect(cues[0].text).toBe('大家好欢迎来到');
		});
	});
});

describe('cuesToSentences', () => {
	it('re-cuts the cues into sentences and times each one', () => {
		expect(cuesToSentences(parseSubtitles(SRT))).toEqual([
			{ text: 'Fuimos al restaurante y pedimos sopa.', start: 1000, end: 3500 },
			{ text: 'La cuenta no era cara.', start: 3500, end: 6000 },
			{ text: 'Dejamos una propina.', start: 3500, end: 6000 }
		]);
	});

	it('spans a sentence that runs across two cues from the first to the last', () => {
		const cues = [
			{ start: 1000, end: 3000, text: 'Fuimos al restaurante' },
			{ start: 3000, end: 5000, text: 'y pedimos sopa.' }
		];
		expect(cuesToSentences(cues)).toEqual([
			{ text: 'Fuimos al restaurante y pedimos sopa.', start: 1000, end: 5000 }
		]);
	});

	it('joins CJK cues without inventing a space', () => {
		expect(cuesToSentences(parseSubtitles(VTT))).toEqual([
			{ text: '我们去了饭馆。', start: 1000, end: 3000 },
			{ text: '我点了汤。', start: 1000, end: 3000 },
			{ text: '她点了鱼和米饭。', start: 3000, end: 5000 }
		]);
	});

	it('falls back to one sentence per cue when nothing is punctuated', () => {
		const cues = parseSubtitles(ROLLING_VTT);
		expect(cuesToSentences(cues)).toEqual([
			{ text: '大家好欢迎来到', start: 30, end: 3270 },
			{ text: '我的频道', start: 3280, end: 6140 },
			{ text: '今天我们聊聊', start: 6150, end: 9000 }
		]);
	});

	it('drops empty cues and has nothing to say about an empty file', () => {
		expect(cuesToSentences([{ start: 0, end: 1, text: '   ' }])).toEqual([]);
		expect(cuesToSentences([])).toEqual([]);
	});

	it('never invents or loses text: every sentence is a substring of the join, in order', () => {
		// The property the offset walk depends on. `splitSentences` is a *cut*, so
		// each piece occurs in the joined string after the one before it — which is
		// what lets a cursor and `indexOf` recover where each sentence came from.
		const cues = parseSubtitles(SRT);
		const joined = cues.map((cue) => cue.text).join(' ');
		let cursor = 0;
		for (const sentence of splitSentences(joined)) {
			const at = joined.indexOf(sentence, cursor);
			expect(at).toBeGreaterThanOrEqual(0);
			cursor = at + sentence.length;
		}
	});
});
